### PR TITLE
Feat/authentication

### PR DESCRIPTION
**Pull request by JAPH254**

### CODE REVIEW

**Review by JAPH254 — COMMENTED** [review]
approved this changes

**Review by heavity — APPROVED** [review]

**Comment by JAPH254** [comment]
@CodiumAI-Agent /describe

**Comment by JAPH254** [comment]
@CodiumAI-Agent /review

**Comment by JAPH254** [comment]
@CodiumAI-Agent /improve

**Comment by JAPH254** [comment]
@CodiumAI-Agent /ask

**Comment by JAPH254** [comment]
@CodiumAI-Agent /describe
--pr_description.extra_instructions="
For the title, use the format [type]: [summary]
"
--pr_description.publish_labels=true
--pr_description.publish_description_as_comment=true
--pr_description.generate_ai_title=true
--pr_description.final_update_message=true

**Comment by JAPH254** [comment]
@CodiumAI-Agent /improve
--pr_code_suggestions.extra_instructions="
Emphasize the following:
- Does the code logic cover relevant edge cases?
- Is the code logic clear and easy to understand?
- Is the code logic efficient?
- 
"
--pr_code_suggestions.num_code_suggestions_per_chunk="4"
--pr_code_suggestions.commitable_code_suggestions=true
--pr_code_suggestions.suggestions_score_threshold="0"

**Pull request merged**
